# Gptcmd configuration

# This option is used by the application for version tracking.
schema_version = "0.1.0"

# This option controls the formatting of the prompt.
# The following keywords (when placed in braces) are replaced by:
# model: the name of the active model
# thread: the name of the active thread (if not the detached thread)
# Python escape sequences are supported.
# Any other characters placed in this string are printed literally.
prompt = "{thread}({model}) "

# This option controls whether estimated session cost is displayed, when
# available, after each successful request.
show_cost = true

# Sometimes, such as when switching to a model that doesn't have cost
# information available, cost estimation is unsupported.
# Since these requests aren't counted in the session cost estimate, when
# switching back to a scenario that does support cost estimation, the reported
# estimated cost will be incomplete.
# This option controls whether these incomplete estimates are displayed.
show_incomplete_cost = false

# This option controls whether the number of prompt (input) and sampled
# (generated) tokens used for each request is displayed when available.
show_token_usage = true
